version: 2.1


jobs:
  build-and-test-310: &template
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: pip install --upgrade pip && pip install .
          name: python/install-deps
      - run:
          command: pip install -U flake8 codecov
          name: Install tools
      - run:
          command: flake8 --ignore=E501 --exclude=__init__.py .
          name: Flake8
      - run:
          command: pushd /tmp && python -c 'import pypinksign' && popd
          name: Import test
      - run:
          command: coverage run -m pypinksign.test_pinkSign
          name: Test
      - run:
          command: codecov
          name: Send coverage
  build-and-test-311:
    <<: *template
    docker:
      - image: cimg/python:3.11
  build-and-test-39:
    <<: *template
    docker:
      - image: cimg/python:3.9
  build-and-test-38:
    <<: *template
    docker:
      - image: cimg/python:3.8
  build-and-test-37:
    <<: *template
    docker:
      - image: cimg/python:3.7
  build-and-test-312:
    <<: *template
    docker:
      - image: cimg/python:3.12
  build-and-test-313:
    <<: *template
    docker:
      - image: cimg/python:3.13
workflows:
  main:
    jobs:
      - build-and-test-313
      - build-and-test-312
      - build-and-test-311
      - build-and-test-310
      - build-and-test-39
      - build-and-test-38
      - build-and-test-37
